[package]
name = "game"
version = "0.1.0"
authors = ["LLuz55 <lucasluz55@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Keep Bevy dynamic linking enabled for faster local rebuilds. Disable it for
# release artifacts that should ship as standalone binaries.
bevy = { version = "0.5.0", features = ["dynamic", "wayland"] }
