[package]
name = "game"
version = "0.1.0"
authors = ["LLuz55 <lucasluz55@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.13.1", features = ["dynamic", "wayland"] }
