mqtt:
  enabled: False

detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: usb

cameras:
  frente_esquerda: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://10.1.1.12:554/user=admin&password={FRIGATE_PASSWORD}&channel=1&stream=1.sdp
          roles:
          - detect
          - record
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 5
    snapshots:
      enabled: True
      bounding_box: False
      required_zones:
       - varanda
       - portao
    rtmp:
      enabled: False
    zones:  
      calcada_direita:
        coordinates: 1280,242,1280,0,756,0,727,232
        objects:
          - person
      calcada_esquerda:
        coordinates: 346,45,0,68,0,248,294,234
        objects:
          - person
      portao_dentro:
        coordinates: 81,720,638,720,511,470,117,450
        objects:
          - person
          - cat
      portao_fora:
        coordinates: 274,257,351,172,686,165,732,251
        objects:
          - person
    record:
      enabled: True
      events:
        retain:
          mode: motion
          default: 10
        objects:
          - person
          - cat
  frente_direita:
    ffmpeg:
      inputs:
        - path: rtsp://10.1.1.11:554/user=lluz&password={FRIGATE_PASSWORD}&ch02.264?dev=1/live
          roles:
          - detect
        - path: rtsp://10.1.1.11:554/user=lluz&password={FRIGATE_PASSWORD}&ch01.264?dev=1/live
          roles:
          - record
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 5
    zones:  
      varanda:
        coordinates: 1280,720,1280,245,950,720
        objects:
          - person
          - cat
      frente_portao:
        coordinates: 1091,393,1004,365,823,434,842,527
        objects:
          - person
          - motorcycle
    motion:
      mask:
        - 0,720,0,309,209,262,469,209,649,232,889,349,816,540,376,720
    snapshots:
      enabled: True
      bounding_box: False
      required_zones:
       - varanda_d 
       - portao_d
    record:
      enabled: True
      events:
        retain:
          default: 10
          mode: motion
        objects:
          - person
          - cat
objects:
  track:
    - person
    - cat
    - motorcycle
  filters:
    person:
      min_area: 5000
      max_area: 100000
