mqtt:
  enabled: true
  user: lluz
  password: '{FRIGATE_MQTT_PASSWORD}'
  host: 10.1.1.10
  port: 1883

detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: usb

ui:
  time_format: 24hour
  strftime_fmt: '%H:%M:%S - %a %d %B %Y'

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

go2rtc:
  streams:
    garagem:
      - ffmpeg:rtsp://10.1.1.14:554/user=lluz&password={FRIGATE_PASSWORD}&channel=1&stream=1.sdp
      - ffmpeg:back#video=h264#audio=aac#hardware
    frente_esquerda:
      - ffmpeg:rtsp://10.1.1.11:554/user=lluz&password={FRIGATE_PASSWORD}&ch02.264?dev=1/live
      - ffmpeg:back#video=h264#audio=copy#audio=aac#hardware
    casa:
      - rtsp://lluz:Luke123luz_@10.1.1.15:554/Streaming/Channels/101
      - ffmpeg:casa#audio=opus
    # maya:
    #   - rtsp://lluz:{FRIGATE_PWD_2}@10.1.1.13:554/0
    #   - ffmpeg:casa#audio=opus
    # frente_direita:
      # - ffmpeg:rtsp://10.1.1.12:554/user=admin&password={FRIGATE_PASSWORD}&channel=1&stream=1.sdp
      # - ffmpeg:casa#video=h264#audio=copy#audio=aac#hardware

cameras:
  garagem: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: 
            rtsp://10.1.1.14:554/user=lluz&password={FRIGATE_PASSWORD}&channel=1&stream=1.sdp
          roles:
            - detect
        #- path: rtsp://10.1.1.14:554/user=lluz&password=Luke123luz_&ch01.264?dev=1/live
        #  roles:
        #  - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 5
    snapshots:
      enabled: true
      bounding_box: false
    record:
      enabled: true
      alerts:
        retain:
          days: 10
      detections:
        retain:
          days: 10
  frente_esquerda: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: 
            rtsp://10.1.1.11:554/user=lluz&password={FRIGATE_PASSWORD}&ch02.264?dev=1/live
          roles:
            - detect
        - path: 
            rtsp://10.1.1.11:554/user=lluz&password={FRIGATE_PASSWORD}&ch01.264?dev=1/live
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 5
    snapshots:
      enabled: true
      bounding_box: false
      required_zones:
        - calcada_direita
        - calcada_esquerda
        - portao_fora
        - portao_dentro
    zones:
      portao_fora:
        coordinates: 0.41,0.788,0.6,0.796,0.614,0.935,0.25,0.917,0.282,0.762
        objects:
          - person
          - car
        inertia: 3
        loitering_time: 0
      calcada_direita:
        coordinates: 1,0.905,1,1,0.823,1,0.623,1,0.624,0.793,1,0.754
        objects:
          - person
          - car
        inertia: 3
        loitering_time: 0
      calcada_esquerda:
        coordinates: 0.288,0.789,0.074,0.796,0.074,0.924,0.276,0.945
        objects:
          - person
          - car
        inertia: 3
        loitering_time: 0
    motion:
      mask: 0,0.372,0.13,0.227,0.167,0.573,0.05,0.829,0,0.925,0,0.529
    record:
      enabled: true
      alerts:
        retain:
          days: 10
      detections:
        retain:
          days: 10
  casa:
    ffmpeg:
      inputs:
        - path: rtsp://lluz:Luke123luz_@10.1.1.15:554/Streaming/Channels/101
          roles:
            - detect
        - path: rtsp://lluz:Luke123luz_@10.1.1.15:554/Streaming/Channels/101
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 5
    zones: {}
    snapshots:
      enabled: true
      bounding_box: false
    record:
      enabled: true
      alerts:
        retain:
          days: 7
      detections:
        retain:
          days: 7
  # maya:
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://lluz:{FRIGATE_PWD_2}@10.1.1.13:554/0
  #         roles:
  #           - detect
  #       - path: rtsp://lluz:{FRIGATE_PWD_2}@10.1.1.13:554/0
  #         roles:
  #           - record
  #   detect:
  #     enabled: true # <---- disable detection until you have a working camera feed
  #     width: 1280 # <---- update for your camera's resolution
  #     height: 720 # <---- update for your camera's resolution
  #     fps: 5
  #   zones: {}
  #   snapshots:
  #     enabled: true
  #     bounding_box: false
  #   record:
  #     enabled: true
  #     alerts:
  #       retain:
  #         days: 7
  #     detections:
  #       retain:
  #         days: 7
objects:
  track:
    - person
    - dog
    - car
  filters:
    person:
      min_area: 5000
      max_area: 100000
      # min_score: 0.75
      # threshold: 0.75
      threshold: 0.8
version: 0.16-0
camera_groups:
  Parent:
    order: 1
    icon: LuDoorClosed
    cameras:
      - frente_esquerda
      - garagem
  Street:
    order: 2
    icon: LuCar
    cameras: frente_esquerda
semantic_search:
  enabled: true
  reindex: false
  model_size: small
detect:
  enabled: true
