homeassistant:
  discovery_topic: homeassistant
  legacy_entity_attributes: true
  legacy_triggers: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://0.0.0.0
  user: lluz
  keepalive: 60
  reject_unauthorized: true
  version: 4
serial:
  port: /dev/ttyACM0
frontend: true
devices:
  '0xa4c138cea8629bb4':
    friendly_name: switch.main_entry
  '0xa4c138288f164e42':
    friendly_name: switch.bathroom
  '0xa4c1384828367953':
    friendly_name: contact.parents_main_door
  '0x00158d000633b922':
    friendly_name: motion.bathroom
    occupancy_timeout: 1
    no_occupancy_since: []
  '0xa4c1382a40441b56':
    friendly_name: contact.main_door
  '0xa4c138a80e665643':
    friendly_name: plugs.tv_fan_switch
    state_action: false
  '0xa4c138bd4ae0b0f1':
    friendly_name: switch.parents_main_entry
  '0x28dba7fffe60b5d5':
    friendly_name: repeater_2_floor
  '0xa4c138da0ccc3e82':
    friendly_name: button_2_2nd_floor
  '0xa4c1380940bc76f8':
    friendly_name: button_1_2nd_floor
  '0xa4c138a8776278b4':
    friendly_name: switch.bedroom
  '0x8c65a3fffec0e05f':
    friendly_name: button_4_tiles
  '0xa4c138efb97a0977':
    friendly_name: outlet_washer
  '0xa4c138d41764dd15':
    friendly_name: outlet_master_pc
advanced:
  log_level: debug
